---
- hosts: test
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Start httpd service
      service:
        name: httpd
        state: started

    - name: Copy index.html
      copy:
        src: /opt/index.html
        dest: /var/www/html/

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
